[OPS 293] multiversion maven repo
zepben/ewb-super-pom pull request #53
Opened 2024-12-16 07:41 UTC by alourie

# Description

We've been building a pipeline container with superpom dependencies as a local Maven repo, which theoretically improves build times for the dependent projects.  However, many projects are not up to date with the latest superpom, resulting in a dependency chain with a number of different superpom version, and hence "cache misses" for the packages.

This change will layer the dependencies from multiple superpom releases in the same local Maven repository, which should result in less cases of dependent packages missing during the following Maven builds. 

# Associated tasks

DO NOT MERGE UNTIL is merged a new `pipeline-java` is built.

# Checklist

If any of these are not applicable, strikethrough the line `~like this~`. **Do not delete it!**. Let the reviewer decide if you should have done it.

### Code
- [x] I have performed a self review of my own code (including checking issues raised when creating the PR).
- [ ] I have added/updated unit tests for these changes, and if not I have explained why they are not necessary.
- [x] I have commented my code in any hard-to-understand or hacky areas.
- [x] I have handled all new warnings generated by the compiler or IDE.
- [x] I have rebased onto the target branch (usually main).

### Documentation
- [ ] I have updated the changelog.
- [x] I have updated any documentation required for these changes.

# Breaking Changes
- [x] I have considered if this is a breaking change and will communicate it with other team members if so.

This is not a breaking change, and should automagically work with all other workflows.

2024-12-16 07:41 UTC, ryanjcoleman commented
Task linked: [OPS-293 Update superpom container build flows to include all the necessary use cases](https://app.clickup.com/t/6929263/OPS-293)

2024-12-17 01:48 UTC, charlta requested changes

2024-12-17 01:48 UTC, charlta commented on .github/workflows/build-container.yml
> +            echo "commits<<EOF" >> $GITHUB_OUTPUT
todo: Update comment for why `commit` doesn't have `=` and add comment for why version is not here

2024-12-17 01:48 UTC, charlta commented on README.md
> + 1. Automatically for superpom releases via a series of flows dispatches. In this case, we want to only update the current repository with new packages/versions, preserving all the packages that are
```suggestion
 1. Automatically for superpom releases via a series of flow dispatches. In this case, we want to only update the current repository with new packages/versions, preserving all the packages that are already there. This allows us to cache packages for many superpom releases in the same repository.
```

2024-12-17 01:48 UTC, charlta commented on README.md
> + 3. Manually, by providing an initial commit; then a new container is build via a series of steps by checking out all the commits starting with the provided SHA and ending on HEAD. Can be used in cas
```suggestion
 3. Manually, by providing an initial commit; then a new container is built via a series of steps by checking out all the commits starting with the provided SHA and ending on HEAD. Can be used in cases where the container gets too big by carrying old and unnecessary dependencies and we want to start afresh.
```

2024-12-17 01:48 UTC, charlta commented on changelog.md
> +- Improved container build flows
Discussed, move CI changes to a new file.

2025-01-01 00:42 UTC, alourie commented on .github/workflows/build-container.yml
> +      commits: ${{ steps.check.outputs.commits }}
Done

2025-01-01 00:42 UTC, alourie commented on .github/workflows/build-container.yml
> +            echo "commits<<EOF" >> $GITHUB_OUTPUT
Done

2025-01-01 00:42 UTC, alourie commented on .github/workflows/build-container.yml
> +          cat Dockerfile.in | envsubst > Dockerfile
Done

2025-01-22 06:28 UTC, alourie commented on README.md
> + 3. Manually, by providing an initial commit; then a new container is build via a series of steps by checking out all the commits starting with the provided SHA and ending on HEAD. Can be used in cas
Done

2025-01-22 06:28 UTC, alourie commented on README.md
> + 1. Automatically for superpom releases via a series of flows dispatches. In this case, we want to only update the current repository with new packages/versions, preserving all the packages that are
Done

2025-01-22 06:28 UTC, alourie commented
I believe this is ready for an additional review and hopefully a merge.

2025-02-04 06:27 UTC, charlta approved these changes
With no way to manually/locally confirm this is working, it will be a matter of merge it and fix anything that goes wrong.

At time of approval the associated task was not been merged, and no new `pipeline-java` has been built, so make sure that happens before merging.

2025-04-03 05:15 UTC, alourie commented
It's as ready as it can be

2025-04-03 08:11 UTC, alourie commented
Now tested in-branch using the build script from the last commit to build all commits.

2025-04-07 03:03 UTC, charlta requested changes

2025-04-07 03:03 UTC, charlta commented on .github/workflows/build-container.yml
> +          cp for-ci-build-image/maven-build.sh .
todo: Unless I am mistaken this is copying the script to the a directory that is under git control, so the hard reset will remove it if you process more than a single commit.

If this is the case, this needs to be updated, otherwise can you please add an explanation to describe how this is not the case

2025-04-07 03:03 UTC, charlta commented on .github/workflows/build-container.yml
> +            cd ..
todo: Assuming the above was made to work, this is changing into a directory that potentially has files that doesn't match what is in the script.

2025-04-07 04:14 UTC, alourie commented on .github/workflows/build-container.yml
> +          cp for-ci-build-image/maven-build.sh .
I've double-checked. `git reset --hard` will only remove the changes in the tracked files if there are any, or the actual untracked files if they're in a way of a tracked file.

Considering we're creating a new file in the root of the project (`maven-build.sh`), which is not in a way of anything else, this file will indeed persist through all the git reset commands as it's not tracked.

2025-04-07 06:52 UTC, charlta approved these changes

2025-04-07 13:46 UTC, merged